RentCarWeb/RentCarWeb/Controllers/VehiculoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WilmerRentCar.BLL;
using WilmerRentCar.BOL;
using WilmerRentCar.BOL.Dtos;

namespace RentCarWeb.Controllers
{
    public class VehiculoController : Controller
    {

        private Manejador<Marca, MarcaDto> _ManejadorMarca;
        private Manejador<Modelo, ModeloDto> _ManejadorModelo;
        private Manejador<TipoVehiculo, TipoVehiculoDto> _ManejadorTipoVehiculo;
        private Manejador<Imagenes, ImagenesDto> _ManejadorImagenes;


        public VehiculoController ()
        {
            _ManejadorImagenes = new Manejador<Imagenes, ImagenesDto>();
        }

        [HttpPost]
        public ActionResult UploadFiles(int vehiculoId)
        {
            HttpFileCollectionBase files = Request.Files;
            List<ImagenesDto> imagenes = new List<ImagenesDto>();
            for (int i = 0; i < files.Count; i++)
            {
                HttpPostedFileBase file = files[i];
                using (var binaryReader = new BinaryReader(file.InputStream))
                {
                    imagenes.Add(new ImagenesDto
                    {
                        Contenido = binaryReader.ReadBytes(file.ContentLength),
                        Formato = file.ContentType,
                        VehículoId = vehiculoId
                    });
                }
            }

            _ManejadorImagenes.CrearRange(imagenes);
            return Json(files.Count + " imagenes creadas");
        }

        // GET: Vehiculo
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Crear()
        {
            _ManejadorMarca = new Manejador<Marca, MarcaDto>();
            _ManejadorModelo = new Manejador<Modelo, ModeloDto>();
            _ManejadorTipoVehiculo = new Manejador<TipoVehiculo, TipoVehiculoDto>();

            ViewBag.TipoVehiculo = _ManejadorTipoVehiculo.ObtenerTodos();
            ViewBag.Marca = _ManejadorMarca.ObtenerTodos();
            //ViewBag.Modelo = _ManejadorModelo.ObtenerTodos();
            return View();
        }
        
        [HttpGet]
        public JsonResult ObtenerModelos(int idMarca)
        {
            _ManejadorModelo = new Manejador<Modelo, ModeloDto>();
            var modelos = _ManejadorModelo.ObtenerTodosPorFiltro(x => x.MarcaId == idMarca);
            return Json(modelos,JsonRequestBehavior.AllowGet);
        }

    }
}

RentCarWeb/RentCarWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("RentCar", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Editar perfil", "EditarPerfil", "Account", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Vehiculos rentados", "Vehiculos", "Account", new { area = "" }, null)</li>
                    @if (@System.Configuration.ConfigurationManager.AppSettings[""+ViewBag.Rol].Contains("Administrador"))
                    {
                    <li>@Html.ActionLink("Crear vehiculo", "Crear", "Vehiculo", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Devolución vehiculo", "Devolver", "Vehiculo", new { area = "" }, null)</li>
                    }
                    <li>@Html.ActionLink("Cerrar Sesión", "SignOut", "Account", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")

    <script type="text/javascript">
        var directorioVirtual = '@Url.Content("~")';
        var origen = "";

        if (!window.location.origin)
            window.location.origin = window.location.protocol + '//' + window.location.host ;

        origen = window.location.origin + directorioVirtual;

    </script>

    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/app/sweetAlert.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>